# -*- coding: utf-8 -*-
"""Expected_ctc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cBPbwGFPjQU1o7qhYYzYBqDBGRzmitsY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

data = pd.read_csv('expected_ctc.csv')

data.head()

data.shape

data.describe()

data.info()

data.columns

data.isnull().sum()

data.duplicated().sum()

data = pd.get_dummies(data, columns=['Department'], prefix='Department', dummy_na=False)
display(data.head())

display(data.head())



# Identify remaining categorical columns
categorical_cols = data.select_dtypes(include=['object']).columns.tolist()

# Apply one-hot encoding to the remaining categorical columns
data = pd.get_dummies(data, columns=categorical_cols, dummy_na=False)

display(data.head())



# Separate features (X) and target (y)
X = data.drop('Expected_CTC', axis=1)
y = data['Expected_CTC']

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

y = y.values.reshape(-1, 1)

print(y.shape)

# Get all column names
all_columns = data.columns.tolist()

# Filter for columns that start with 'Department_'
department_columns = [col for col in all_columns if col.startswith('Department_')]

print(department_columns)

display(data[department_columns].head())

role_columns = [col for col in all_columns if col.startswith('Role_')]
print(role_columns)
display(data[role_columns].head())

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

from sklearn.linear_model import LinearRegression
lm=LinearRegression()
lm.fit(X_train,y_train)
y_pred=lm.predict(X_test)

from sklearn.impute import SimpleImputer

# Initialize the imputer
imputer = SimpleImputer(strategy='mean')

# Fit the imputer on the training data and transform both training and testing data
X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)

# Now fit the Linear Regression model with the imputed data
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_train_imputed, y_train)

# Make predictions
y_pred = lm.predict(X_test_imputed)

a=lm.coef_
b=lm.intercept_
print("Estimate model slope,a:",a)
print("Estimate model intercept,b:",b)

from sklearn.metrics import mean_squared_error,r2_score
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
print("MSE:",mse)
print("RMSE:",rmse)
r2=r2_score(y_test,y_pred)
print("R2:",r2)

plt.scatter(y_test, y_pred)
plt.xlabel("Actual Expected CTC")
plt.ylabel("Predicted Expected CTC")
plt.title("Actual vs Predicted Expected CTC (Test Set)")
plt.show()

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Make predictions on the training set
y_train_pred = lm.predict(X_train_imputed)

# Calculate metrics for the training set
mse_train = mean_squared_error(y_train, y_train_pred)
rmse_train = np.sqrt(mse_train)
r2_train = r2_score(y_train, y_train_pred)

print("Training Set Metrics:")
print("MSE (Train):", mse_train)
print("RMSE (Train):", rmse_train)
print("R2 (Train):", r2_train)

print("\nTest Set Metrics (for comparison):")
print("MSE (Test):", mse)
print("RMSE (Test):", rmse)
print("R2 (Test):", r2)