# -*- coding: utf-8 -*-
"""linear_regression_simple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtPhTz26JiExgWu9BDQbgWQyLViVrdEk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import seaborn as sns

url='sales.txt'
df=pd.read_csv(url, sep='\s+',header=None)
print(df.shape)
print(df.head())
df.columns=['Sales','Advertising']
print(df.head())
print(df.info())

print(df.describe())

x=df['Sales'].values
y=df['Advertising'].values
plt.scatter(x,y, color='blue',label='Scatter')
plt.xlabel('Sales')
plt.ylabel('Advertising')
plt.title('Relationship between Sales and Advertisement')
plt.legend(loc=4)
plt.scatter(x,y)
plt.show()

print(x.shape)
print(y.shape)
x=x.reshape(-1,1)
y=y.reshape(-1,1)
print(x.shape)
print(y.shape)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(x_train,y_train)
y_pred=lm.predict(x_test)
print(y_pred)

a=lm.coef_
b=lm.intercept_
print("Estimate model slope, a:", a)
print("Estimate model intercept, b:", b)

lm .predict(x)[0:5]

import numpy as np # Import numpy to create a 2D array
print(str(lm.predict([[24]]))) # Reshape the input to a 2D array

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print("RMSE value: {:.4f}".format(rmse))

from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R2 score value: {:.4f}".format(r2))

plt.scatter(x,y, color='blue',label='Scatter')
plt.plot(x_test,y_pred,color='red',linewidth=3,label='Regression Line')
plt.title('relationship between sales and Advertisement')
plt.xlabel('Sales')
plt.ylabel('Advertisement')
plt.legend(loc=4)
plt.show()

plt.scatter(lm.predict(x_train),lm.predict(x_train)-y_train,color='red',label='Train data')
plt.scatter(lm.predict(x_test),lm.predict(x_test)-y_test,color='blue',label='Test Data')
plt.hlines(xmin=0,xmax=50,y=0,linewidth=3)
plt.title('Residual Error')
plt.legend(loc=4)
plt.show()

print("Training set score:{:.4f}".format(lm.score(x_train,y_train)))
print("Test set score: {:.4f}".format(lm.score(x_test,y_test)))